apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  namespace: crossplane-system
spec:
  package: "crossplanecontrib/provider-kubernetes:main"
  runtimeConfigRef:
    name: provider-kubernetes-local
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-kubernetes-local
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-kubernetes-supervisor
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: supervisor-kubeconfig
      key: kubeconfig
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-local
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: 
        matchLabels:
          pkg.crossplane.io/provider: provider-kubernetes
      template: 
        spec:
          containers:
            - name: package-runtime
              args:
                - --debug
  serviceAccountTemplate:
    metadata:
      name: provider-kubernetes