apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: supervisor
  namespace: crossplane-system
spec:
  provider:
    kubernetes:
      remoteNamespace: <YOUR_VSPHERE_NAMESPACE>
      server:
        url: "<YOUR_SUPERVISOR_CLUSTER_KUBEAPI_URL>"
        caProvider:
          type: ConfigMap
          name: supervisor-kube-root-ca
          key: supervisor.crt
      auth:
        token:
          bearerToken:
            name: eso-supervisor-token
            key: token
