apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: supervisor
  namespace: crossplane-system
spec:
  provider:
    kubernetes:
      remoteNamespace: ns1
      server:
        url: "https://192.168.11.201"
        caProvider:
          type: ConfigMap
          name: supervisor-kube-root-ca
          key: supervisor.crt
      auth:
        token:
          bearerToken:
            name: eso-supervisor-token
            key: token